%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.19.1

-ifndef(on_message_drop_pb).
-define(on_message_drop_pb, true).

-define(on_message_drop_pb_gpb_version, "4.19.1").

-ifndef('EVENTSSIDECAR.V1.ONMESSAGEDROP_PB_H').
-define('EVENTSSIDECAR.V1.ONMESSAGEDROP_PB_H', true).
-record('eventssidecar.v1.OnMessageDrop',
        {timestamp = undefined  :: on_message_drop_pb:'google.protobuf.Timestamp'() | undefined, % = 1, optional
         client_id = <<>>       :: unicode:chardata() | undefined, % = 2, optional
         mountpoint = <<>>      :: unicode:chardata() | undefined, % = 3, optional
         topic = <<>>           :: unicode:chardata() | undefined, % = 5, optional
         payload = <<>>         :: iodata() | undefined, % = 6, optional
         qos = 0                :: integer() | undefined, % = 7, optional, 32 bits
         reason = 'EXPIRED'     :: 'EXPIRED' | 'QUEUE_FULL' | 'MAX_PACKET_SIZE_EXCEEDED' | integer() | undefined % = 8, optional, enum eventssidecar.v1.Reason
        }).
-endif.

-ifndef('GOOGLE.PROTOBUF.TIMESTAMP_PB_H').
-define('GOOGLE.PROTOBUF.TIMESTAMP_PB_H', true).
-record('google.protobuf.Timestamp',
        {seconds = 0            :: integer() | undefined, % = 1, optional, 64 bits
         nanos = 0              :: integer() | undefined % = 2, optional, 32 bits
        }).
-endif.

-endif.
