name: checks format & runs tests

on:
  push:
    branches:
      - 'main'
  pull_request:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  code_checks:
    name: Check code style and quality
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 27.0
          version-type: strict
      - run: sudo apt-get -y install libsnappy-dev
      - name: Check code formatting (erlfmt)
        run: ./rebar3 fmt -c
      - name: Run dialyzer type checker
        run: ./rebar3 dialyzer
  coverage:
    runs-on: ubuntu-20.04
    needs: code_checks
    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: vmq_test_user
          POSTGRES_PASSWORD: vmq_test_password
          POSTGRES_DB: vmq_test_database
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      memcached:
        image: memcached
        ports:
          - 11211:11211
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redissentinel:
        image: bitnami/redis-sentinel
        ports:
          - 26379:26379
        options: >-
          --health-cmd "redis-cli -p 26379 ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 27.0
          version-type: strict
      - run: sudo apt-get -y install libsnappy-dev
      - run: sudo apt-get -y install pcregrep
      - run: make rel
      - run: make db-setup
      - run: pwd
      - run: sh ./run-tests-with-retry.sh .
